### ISSUE TITLE
Code coverage check isn't working 

### ISSUE THREAD

**Issue by nicholaskl97** [nicholaskl97/NeuralLyapunov.jl#22]
**Describe the bug 🐞**

Codecov isn't generating new reports, for some reason. It hasn't for a month.

**Comment by nicholaskl97** [comment]
The last commit to generate a Codecov report was merging #16. 

It might have to do with #17, which was a change to the CI workflow, intended to stop failures on nightly from registering as failed tests, since that was the first to fail.

**Comment by nicholaskl97** [comment]
Alternatively, looking at CI logs, "Error: Codecov token not found. Please provide Codecov token with -t flag." could be the issue.

**Comment by ChrisRackauckas** [comment]
It needs to be fixed with a token. @thazhemadam

**Comment by thazhemadam** [comment]
Fixed by #23.

**Comment by nicholaskl97** [comment]
Thank you both!
